Fix implementation of fn every
jesseduffield/OK pull request #8
Opened 2022-08-04 12:08 UTC by lrusso96

I think there is a typo in this example: the switch clause is wrong.
Check the code on an array of integers all greater than 2 and the result would be false as well.
https://github.com/jesseduffield/OK/blob/d150075b0824c6a5c4d45a599755da33b1e1ff8f/README.md?plain=1#L381-L391

2022-11-12 07:39 UTC, jesseduffield commented on README.md
> +    switch check(e) { case false: passed = false; } }
good catch!

2022-11-12 07:39 UTC, jesseduffield commented on README.md
> +result1 = every([5,2,4,1,3], fn(e) { return e >= 2 }); // false
To keep things simple I would just leave this bit as it was

2022-11-12 07:40 UTC, jesseduffield requested changes
Thanks for making this. Just one thing

2022-11-17 15:51 UTC, lrusso96 commented
I close this as explained in #19.

2022-11-17 15:51 UTC, closed without merging