Marginally improve Quentyn's writing
jesseduffield/OK pull request #9
Opened 2022-08-29 20:10 UTC by tonogram

Quentyn may not deserve kindness, but he at least deserves more consistent punctuation and grammar.

2022-11-12 07:50 UTC, jesseduffield requested changes
Thanks for making this :) One comment

2022-11-12 07:50 UTC, jesseduffield commented on ok/quentyn/quentyn.go
> +	"The things that happen today are the same things that happened a thousand years ago, and they will continue to happen a thousand years from now.",
I think it's more poetic to leave out the 'they' here

2022-11-15 16:55 UTC, tonogram commented
Did the thing 👉😎👉

2022-11-15 21:58 UTC, merged

2022-11-15 21:58 UTC, jesseduffield commented
Thanks for making this @tonogram. Now I simply need to remember how to deploy this change haha